name: Deploy User & Community

on:
  push:
    branches: [ main ]
    paths:
      - 'msa-user/**'
      - 'msa-community/**'
      - '.github/workflows/ec2-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Repository 코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 17 설정
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      # application.properties 파일 동적 생성
      - name: User 서비스 설정 파일 생성
        run: |
          mkdir -p msa-user/src/main/resources
          echo "${{ secrets.MSA_USER_CONFIG }}" > msa-user/src/main/resources/application.properties
          echo "User 서비스 설정 파일 생성 완료"

      - name: Community 서비스 설정 파일 생성
        run: |
          mkdir -p msa-community/src/main/resources
          echo "${{ secrets.MSA_COMMUNITY_CONFIG }}" > msa-community/src/main/resources/application.properties
          echo "Community 서비스 설정 파일 생성 완료"

      # 서비스 빌드
      - name: User 서비스 빌드
        run: |
          cd msa-user
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: Community 서비스 빌드
        run: |
          cd msa-community
          chmod +x ./gradlew
          ./gradlew clean build -x test

      # EC2로 파일 업로드
      - name: EC2에 파일 업로드
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "msa-user/build/libs/*.jar,msa-community/build/libs/*.jar,msa-user/Dockerfile,msa-community/Dockerfile,docker-compose.yml"
          target: "/home/${{ secrets.EC2_USER }}/app"
          strip_components: 0

      # EC2에서 서비스 실행
      - name: EC2에서 서비스 실행
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script_stop: true
          script: |
            # Docker 및 Docker Compose 설치 확인
            if ! command -v docker &> /dev/null; then
              echo "Docker 설치 중..."
              sudo yum update -y
              sudo amazon-linux-extras install docker -y
              sudo service docker start
              sudo usermod -a -G docker $USER
            fi
            
            if ! command -v docker-compose &> /dev/null; then
              echo "Docker Compose 설치 중..."
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.18.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi
            
            # 서비스 배포 및 실행
            cd /home/$USER/app
            
            # Dockerfile 수정하여 올바른 경로 설정
            sed -i 's|COPY build/libs/|COPY msa-user/build/libs/|g' msa-user/Dockerfile
            sed -i 's|COPY build/libs/|COPY msa-community/build/libs/|g' msa-community/Dockerfile
            
            # 이전 서비스 중지 및 새 서비스 시작
            docker-compose down
            docker-compose up -d --build
            
            # 로그 확인
            sleep 5
            docker ps
            docker logs msa-user
            docker logs msa-community